name: RasFocus Android APK Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Qt for Android
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        target: 'android'
        arch: 'android_armv7'

    - name: Build APK
      run: |
        qmake RasFocus.pro
        make
        make install INSTALL_ROOT=android-build
        androiddeployqt --output android-build --verbose --input android-libRasFocusApp.so-deployment-settings.json --gradle

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: RasFocus-Android-APK
        path: android-build/build/outputs/apk/debug/*.apk
